name: Pull Request Analytics
on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Request Analytics
      uses: AlexSim93/pull-request-analytics-action@v4.8.0
      with:
        GITHUB_OWNERS_REPOS: bnevis-i/kubernetes
